### PR TITLE
hot fix for missing AppProvider import in main.jsx, not working base …

### PR DESCRIPTION
**Pull request by CAWittMN**
Fixes missing mui dependency, AppContext import into main.jsx, and temporary fix for tests so rules for testing can be added again.

### CODE REVIEW

**Comment by ChapstickLover97** [comment]
Looks all good to me!

**Review by ChapstickLover97 — COMMENTED** [review]
Legit

**Review by ChapstickLover97 — APPROVED** [review]
Legit

**Review by york-eishimwe — APPROVED** [review]
Approved

**Pull request merged**
